version: '2.4'
services:
  ping-openjdk:
    image: krisfoster/ping:openjdk.0.2
    restart: always
    mem_limit: 256m
    memswap_limit: 256m
    cpu_count: 1
    cpu_percent: 100
    cpus: 1
    depends_on:
      - "prom"
    ports:
      - "8085:8080"
  ping-graalce:
    image: krisfoster/ping:graalce.0.2
    restart: always
    mem_limit: 512m
    memswap_limit: 512m
    cpu_count: 1
    cpu_percent: 100
    cpus: 1
    depends_on:
      - "prom"
    ports:
      - "8086:8080"
  ping-graalee:
    image: krisfoster/ping:graalee.0.2
    restart: always
    mem_limit: 512m
    memswap_limit: 512m
    cpu_count: 1
    cpu_percent: 100
    cpus: 1
    depends_on:
      - "prom"
    ports:
      - "8087:8080"
  ping-native-ee:
    image: krisfoster/ping:native.0.2
    restart: always
    mem_limit: 256m
    memswap_limit: 256m
    cpu_count: 1
    cpu_percent: 100
    cpus: 1
    depends_on:
      - "prom"
    ports:
      - "8088:8080"
  prom:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
