{
 "title": "Micronaut Perf comparison",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Req / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "jvm_memory_used_bytes" }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  }
 ]
}